default:
  image: registry.dune-project.org/lukas.riedel/dune-structures:env

variables:
  # Add project directory to dunecontrol path
  DUNE_CONTROL_PATH: /duneci/modules:$CI_PROJECT_DIR
  CMAKE_FLAGS_DEFAULT:
    -DDUNE_PYTHON_VIRTUALENV_SETUP=True
  CMAKE_FLAGS: $CMAKE_FLAGS_DEFAULT
  # Allow recursive cloning of submodules
  GIT_SUBMODULE_STRATEGY: recursive
  CXXFLAGS_DEFAULT: ""
  CXXFLAGS: $CXXFLAGS_DEFAULT

workflow:
  rules:
    # Trigger pipeline after pushes, starting from web, or scheduling
    - if: "$CI_PIPELINE_SOURCE == 'push'
           || $CI_PIPELINE_SOURCE == 'web'
           || $CI_PIPELINE_SOURCE == 'schedule'"

stages:
  - build
  - test

# --- BUILD STAGE ---

# Build release
build:all:
  stage: build
  script:
    - dunecontrol --current all
  artifacts:
    # NOTE: Only upload required apps to reduce artifacts size
    paths:
      - build-cmake/apps/structured2d_p2
      - build-cmake/apps/cell2d_p2
      - build-cmake/apps/gmsh2d_p2
    expire_in: 6h

# Build tests
build:tests:
  extends: build:all
  script:
    - dunecontrol --current configure
    - dunecontrol --current bexec make build_tests
  artifacts:
    # NOTE: Only upload tests to reduce artifacts size
    paths:
      - build-cmake/test

# Build with debugging and warnings (fail on warnings)
build:debug:
  extends: build:all
  allow_failure: true
  variables:
    # Fail on warnings
    CXXFLAGS: $CXXFLAGS_DEFAULT -Wall -Werror
    # NOTE: '-Werror' causes QuadMath compile test to fail, so skip it here
    CMAKE_FLAGS:
      $CMAKE_FLAGS_DEFAULT
      -DCMAKE_BUILD_TYPE=Debug
      -DQuadMath_COMPILES=True
  artifacts:
    paths: []

# --- TEST STAGE ---

# Run all tests
test:all:
  stage: test
  needs: ["build:tests"]
  before_script:
    # NOTE: Reconfigure because build tree is not complete!
    - dunecontrol --current configure
    - cd $CI_PROJECT_DIR/build-cmake
  script:
    - ctest -R test -E python --output-on-failure

# Run simulations
test:run_simulations:
  extends: test:all
  needs: ["build:all"]
  script:
    - ctest -R run --output-on-failure
  artifacts:
    paths:
      - build-cmake/experiments/hansbo_reproduction/
    expire_in: 1 day

# Test Python code
test:python:
  stage: test
  needs: []
  script:
    - dunecontrol --current configure
    - dunecontrol --current bexec make test_python

# Test the CLI
test:cli:
  extends: test:all
  needs: ["build:all"]
  script:
    - source activate
    - structures run structured2d_p2
                     ../experiments/hansbo_reproduction/fig23_1.yml
    - if structures run structured2d_p2 does_not_exist.yml;
      then exit 1; else echo "\nFailed as expected"; fi
    - if structures run does_not_exist ../experiments/hansbo_reproduction/fig23_1.yml;
      then exit 1; else echo "\nFailed as expected"; fi
